### ISSUE TITLE
 No longer loading raw *.lua files in a module 

### ISSUE THREAD

**Issue by konradmalik** [nvim-neorocks/lz.n#10]
sorry if I'm doing something wrong, I've just started to use this plugin.

I think there is a regression introduced in 1.3.0. See below:

Folder structure:
```
lua/
     plugins/
                 plugin1/init.lua
                 plugin2.lua
```

Both files return a single PluginSpec and print text in their `after` calls.

My code to load this:
```lua
require("lz.n").load("plugins")
```

Expected output (this or reversed, does not matter) according to the docs:
```
after from plugin1
after from plugin2
```

Actual output:
```
after from plugin1
```

So the problem is that raw files (not submodules) are no longer loaded.

I can also remove `plugin1` totally, and `plugins2` still won't be loaded at all, so it does not matter if submodules are present or not.

Workaround that works for me:
```lua
-- add lua/plugins/init.lua which manually requires and returns all plugins from that folder
-- then:
require("lz.n").load(require("plugins"))
```

**Comment by mrcjkb** [comment]
That's very strange :thinking: 
I have [test cases for this](https://github.com/nvim-neorocks/lz.n/blob/faed7d49f04fb914fa1e443bfe653525e7f63863/spec/import_spec.lua?plain=1#L51) and they are passing.

**Comment by mrcjkb** [comment]
Ah, but it fails if I have both

```
plugin1/init.lua
plugin2.lua
```

in the same `load` call.

**Comment by mrcjkb** [comment]
Hmm, but it's only calling one of the `after` hooks.

**Comment by konradmalik** [comment]
hmm, since you're using Nix maybe this will be helpful:
https://github.com/konradmalik/neovim-flake/tree/lzn

the issue is reproducible on my branch above.

See:
- `config/native/init.lua` for lz.n load call
- `config/native/lua/plugins` for plugins to be loaded (there are print statements in each of the files)

To reproduce:
- `nix run`
- `:mess` - see that it says only "sourcing cmp", should print a bunch more.
- to make sure, open any file e.g. `:e readme.md` and try to execute `Boole` (a command from boole.nvim) - it's not available, but should be

**Comment by mrcjkb** [comment]
Ahh, I know what the problem is.
lz.n checks for files and directories. With nix, the files are symlinks.
