### ISSUE TITLE
`trigger_load` does not find a module with no specified handlers.

### ISSUE THREAD

**Issue by xulongwu4** [nvim-neorocks/lz.n#104]
If I have a plugin A which is purely a dependency of some other plugin B, and I would like to do

```lua
{
   "B",
  event = "InsertEnter",
  before = function() require("lz.n").trigger_load("A") end
}
```

Let's assume "A" does not appear anywhere else in the plugin specs.

This will not work as the `trigger_load` call will try to call `lookup("A")`. However, `lookup` can only find the plugin if it has at least one of the handlers specified (e.g., `keys`, `ft`.) 

As a real-world example, I was trying out the example [here](https://github.com/nvim-neorocks/lz.n/wiki/lazy%E2%80%90loading-nvim%E2%80%90cmp-and-its-extensions), but `trigger_load` cmp sources such as `cmp_luasnip` does nothing because the `lookup` call fails to find the `cmp_luasnip` plugin itself.

**Comment by mrcjkb** [comment]
Hey 👋 

thanks for reporting. Yep, I didn't anticipate this use case. I guess it can be solved by adding a boolean `lazy` field to the plugin spec and adding a handler for that. 
I'll look into it.
