### ISSUE TITLE
[bug] setting `lazy = false` marks plugin as eager

### ISSUE THREAD

**Issue by xronin01** [nvim-neorocks/lz.n#107]
![Screenshot_20241023-152157_Termux](https://github.com/user-attachments/assets/0e2c4e67-8194-4e9e-96ec-ddf648a14a19)
the after function is not loaded with "lazy = false"

**Comment by mrcjkb** [comment]
Hey :wave: 

Thanks for reporting. This is indeed a bug.
However, there is no need to set `lazy = false` if you don't want to lazy-load a plugin.
It will be loaded eagerly if no fields are set.
