### ISSUE TITLE
cannot load on DeferredUIEnter

### ISSUE THREAD

**Issue by BirdeeHub** [nvim-neorocks/lz.n#11]
Failed to enable handlers for image.nvim: ...k/myNeovimPackages/start/lz-n/lua/lz/n/handler/event.lua:131: Invalid 'event': 'DeferredUIEnter'

DeferredUIEnter throws an error when I try to use event = 'DeferredUIEnter' in my specs

Using single plugin spec load functions only, idk if that makes a difference

**Comment by mrcjkb** [comment]
Thanks for reporting :pray: 

https://github.com/nvim-neorocks/lz.n/commit/cf11ec2b1696dddd5620a055244cc0860f982677
