### ISSUE TITLE
Broken code in wiki

### ISSUE THREAD

**Issue by Eddio0141** [nvim-neorocks/lz.n#118]
# Broken code
Page: https://github.com/nvim-neorocks/lz.n/wiki/lazy%E2%80%90loading-nvim%E2%80%90cmp-and-its-extensions

1. `if not vim.tbl_isempy(plugin_dirs) then` should be `if not vim.tbl_isempty(plugin_dirs) then`
2. `local plugin_dirs = vim.fn.globpath(path, glob, nil, true, true)` should be `local plugin_dirs = vim.fn.globpath(dir, glob, nil, true, true)`

# Additional notes
- Probably should mention to enable `lazy = true` for the cmp extensions, I didn't know why the plugins weren't working until somebody mentioned in the issues
- I don't think I can create a pull request for the wiki, so it has to be an issue, sorry!

**Comment by mrcjkb** [comment]
thanks 🙏
