### ISSUE TITLE
[Feature] API for querying plugin status

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/lz.n#24]
It says a UI is non-goal for this plugin. Maybe a separate extension plugin for it. But for now, to help debug a config, perhaps an API that can give a list of all plugins managed by `lz.n` and full spec of each plugin plus an `is_loaded` boolean?

_Originally posted by @pseudoparenchymatous in https://github.com/nvim-neorocks/lz.n/discussions/18_

**Comment by BirdeeHub** [comment]
This could be implemented as a handler + using require('lz.n.state')

Whenever a plugin is loaded, del gets called. Simply have the handler keep an internal state of the plugin names that were called, and a function to require('lz.n.state') and zip in a is_loaded field into the ones that were loaded already when it returns the list.

**Comment by BirdeeHub** [comment]
Probably only like 50 lines or so. Should it be added to the plugin or should it just be posted in discussions?

**Comment by BirdeeHub** [comment]
```lua
---@type string[]
local states = {}

local M = {
  ---@type lz.n.Handler
  handler = {
	-- this field does nothing but it does stop others from using is_loaded,
	-- which is good because we overwrite the value in getAllPlugins
	spec_field = "is_loaded",
	---@param plugin lz.n.Plugin
	del = function (plugin)
	  table.insert(states, plugin.name)
	end,
	add = function(_) end,
  },
}

function M.getAllPlugins()
  local result = vim.deepcopy(require("lz.n.state").plugins)
  for _, name in ipairs(states) do
	if result[name] ~= nil then
	  ---@diagnostic disable-next-line: inject-field
	  result[name].is_loaded = true
	end
  end
  return result
end

return M
```

Simply add `require('lz_n').register_handler(require('the.file').handler)` to the start of your config

and then you can call `:lua print(vim.inspect(require('the.file').getAllPlugins()))` and it will print out all the states and whether they were loaded or not

**Comment by mrcjkb** [comment]
@pseudoparenchymatous version 2 of this library provides a `require("lz.n").lookup(plugin_name)` function, which allows you to search for plugins that are pending to be loaded.
It returns `nil` if the passed in plugin isn't pending to be loaded (which is the case if it doesn't exist or it has already been loaded).

I believe that serves the use case described in this issue.
