### ISSUE TITLE
List of one plugin spec is not loaded

### ISSUE THREAD

**Issue by horriblename** [nvim-neorocks/lz.n#31]
when loading a list of one plugin:

```lua
require('lz.n').load({
    {"flutter-tools", keys = "<leader>u"}
})
```

nothing happens, `require 'lz.n.state'.plugins` shows an empty table as well

this looks like the culprit, though I'm not sure what the intended check is supposed to be:

https://github.com/nvim-neorocks/lz.n/blob/4c790ba2c3789f580aa019712bbe3112f85e73a0/lua/lz/n/spec.lua#L157

**Comment by horriblename** [comment]
oh it's probably `... and #spec == 0`

**Comment by mrcjkb** [comment]
`load` also accepts a single plugin spec:

```lua
require('lz.n').load({"flutter-tools", keys = "<leader>u"})
```
