### ISSUE TITLE
Merge import spec and non-import spec

### ISSUE THREAD

**Issue by austinliuigi** [nvim-neorocks/lz.n#33]
When a spec is normalized [here](https://github.com/nvim-neorocks/lz.n/blob/4c790ba2c3789f580aa019712bbe3112f85e73a0/lua/lz/n/spec.lua#L169), if it is included as both a single_plugin_spec and in the import_spec, then whichever appears first in the list will be overridden by the other.

For instance, rocks-lazy.nvim [inserts the import at the very end of the spec list](https://github.com/nvim-neorocks/rocks-lazy.nvim/blob/61c0efc7ae36184af38de7f847f345cd3bada4b9/lua/rocks-lazy/internal.lua#L88), so if a plugin has specs provided in lua via import, then it would override any specs provided in rocks.toml. Additionally, since rocks.nvm injects its before hook along with the toml specs, that would also get overridden, which causes the plugin to not get configured if the user is using rocks-config.nvim.

This seems like it needs to be handled by lz.n instead of rocks-lazy.nvim because lz.n is the one doing the importing, so rocks-lazy.nvim would have no idea about which plugins are configured using lua. My suggestion would be to specify the priority between imported specs and non-imported specs and handle it appropriately with, e.g. a `vim.tbl_deep_extend()` [here](https://github.com/nvim-neorocks/lz.n/blob/4c790ba2c3789f580aa019712bbe3112f85e73a0/lua/lz/n/spec.lua#L177).

Edit: After looking again at rocks-lazy.nvim, I noticed [the README says it will be merged](https://github.com/nvim-neorocks/rocks-lazy.nvim/blob/61c0efc7ae36184af38de7f847f345cd3bada4b9/README.md?plain=1#L262C1-L266C52), but that doesn't seem to be the case.

**Comment by mrcjkb** [comment]
I'm not sure I understand the issue.

rocks-lazy.nvim has [a test case](https://github.com/nvim-neorocks/rocks-lazy.nvim/blob/c59e50df7b25cc4ae1a5dc4dc73d07358d74ad99/spec/rocks_lazy_spec.lua) to verify that you can use both rocks.toml and lua configs.

I've corrected the tip box in the readme. It doesn't merge configs, it just extends them (assuming there are no duplicates).
Is there a use case for having duplicate specs? Merging duplicates would override rocks-config hooks, too.

**Comment by austinliuigi** [comment]
Oh I see. I misunderstood the tip box as saying you can use both rocks.toml entries and lua to configure specs for the same plugin. So is it expected for the config_hook that rocks.nvim injects into rocks.toml entries to not run for plugins that have lua configured specs?

**Comment by austinliuigi** [comment]
> Merging duplicates would override rocks-config hooks, too.

Not if the user doesn't provide an explicit before hook of their own

**Comment by austinliuigi** [comment]
Ok got it. I think it should be mentioned in the rocks-lazy.nvim README that lua configured specs aren't integrated with rocks-config.nvm because that caused me quite a bit of confusion.

> That's a fair point. We could potentially use vim.tbl_deep_extend("error", ...) to prevent the hook from accidentally being overridden (and if users want to override it, they'd have to use only Lua specs).

I'm not quite sure I understand. Are you using this to merge the rocks.toml spec with the lua spec for a plugin? If so, then I don't think "error" would work to allow overriding.

**Comment by mrcjkb** [comment]
> I think it should be mentioned in the rocks-lazy.nvim README

Updated. 

Regarding merging configs: The
