### ISSUE TITLE
make `trigger_load` idempotent 

### ISSUE THREAD

**Issue by mrcjkb** [nvim-neorocks/lz.n#51]
> yes you could still accidentally call trigger_load many times and it would call the plugin's hooks each time.

What if I have two plugins B and C, that depend on A? Using `trigger_load` on the after/before of B and C is not correct, as you might trigger A twice.

And to be clear, I'm not saying `trigger_load` is bad, but rather that it is a low-level tool and we don't have some idempotent alternative.

_Originally posted by @viperML in https://github.com/nvim-neorocks/lz.n/discussions/47#discussioncomment-10365773_

**Comment by mrcjkb** [comment]
CC @BirdeeHub 

Sorry, I know I opened the issue, but I'm no longer sure if this is necessary.
It increases the complexity just for the edge case of needing to influence the order in which plugin scripts are are sourced (which is a bad practice on the plugin authors' side, [as I explained here](https://github.com/nvim-neorocks/lz.n/pull/48#issuecomment-2294878474)).

The more I think of it, the more I realise `trigger_load` should *be used by handlers only*, and should not be called from within a `before` hook. 
With Neovim's built-in loading mechanism, `packadd!` should be fully sufficient to support library dependencies (Again, a plugin *should not* depend on another plugin's `plugin/` scripts - that's a bug, as it's not even supported by Neovim!).

For configuring plugins that have extensions (such as telescope), a better solution might be to support bundles, similar to rocks-config.nvim.

A potentially easy way to achieve this could be to allow `lz.n.PluginSpec` to look like this: 

```lua
{
  {
    "telescope.nvim",
    "telescope-fzy-native.nvim",
    "telescope-hoogle.nvim"
  },
  before = function(...) end,
}
```

The spec's key could be constructed using `vim.inspect(spec[1])`, or the bundle could be given a name.

Please do not go ahead and implement this yet. I will have to think very carefully about whether this is necessary (it probably isn't).

**Comment by BirdeeHub** [comment]
Even for handlers only trigger_load not loading a plugin twice will simplify things.

**Comment by BirdeeHub** [comment]
it will help prevent issues of concurrency where two could be called simultaneously

**Comment by BirdeeHub** [comment]
and makes sure nothing breaks if they were to be nested on accident

**Comment by BirdeeHub** [comment]
packadd stops issues with the plugin itself loading twice.

packadd does not stop issues with calling the spec hooks twice

**Comment by BirdeeHub** [comment]
Im not sure how I feel about bundles. I dont like that as much. Also, this is a simple change, that is not. I also dont see what I get out of supporting bundles over what Im already doing in my personal config, which is just loading more plugins in the load function sometimes

**Comment by BirdeeHub** [comment]
But yeah of the 2 changes here, I feel bundling is better handled via the load function, but this just needs to exist.

Also, OP's original scenario is not solved by bundling.

**Comment by BirdeeHub** [comment]
I need this change to solve this mess which is CAUSED by bundling

https://github.com/BirdeeHub/birdeeSystems/blob/b7fc5aec31a835512672cfaa7fe01a2196fbd938/common/birdeevim/lua/birdee/plugins/completion.lua#L1-L26

**Comment by BirdeeHub** [comment]
basically, there is too much bundling going on and all of my changes proposed today have been to LIMIT required bundling

**Comment by BirdeeHub** [comment]
Also, if they really want to they can still load the plugin spec again simply by setting its state.loaded to nil again

**Comment by BirdeeHub** [comment]
also packadd! forces reload, packadd adds to packpaths only if already loaded

**Comment by BirdeeHub** [comment]
but yeah this slightly increases internal complexity (slightly. Its a list and an if statement basically) but it decreases mental overload on the end user significantly

**Comment by BirdeeHub** [comment]
because otherwise we have to make our own is_loaded variable/list/whatever and check for it in every single spec hook to prevent the hooks from loading again if we wanted to split dependencies into their own specs rather than bundling them

**Comment by mrcjkb** [comment]
> Even for handlers only trigger_load not loading a plugin twice will simplify things.

No it won't. Handlers still need to keep track of their internal state for various reasons (not just preventing multiple loads). Your PR adds more state and more branches to the code.

> it will help prevent issues of concurrency where two could be called simultaneously

Neovim is single threaded. This is a non issue, unless you're trying to do something funky with coroutines.

> packadd stops issues with the plugin itself loading twice.

It doesn't. It's a plugin's responsibility to make sure it doesn't get sourced more than once if it shouldn't. Hence the `g:plugin_loaded` pattern. 

> packadd does not stop issues with calling the spec hooks twice

It doesn't even call the spec hooks.

> I need this change to solve this mess which is CAUSED by bundling

Again, that mess is caused by nvim-cmp's poor design decisions.
You don't even know if this would solve your problem yet.

> Also, if they really want to they can still load the plugin spec again simply by setting its state.loaded to nil again, just like you do with require and package.loaded to force lua modules to run initialization again.

Or, if you want to do something that's out of scope for this library, you can override the `trigger_load` function: 

```lua
local orig_trigger_load = require("lz.n").trigger_load
require("lz.n").trigger_load = function(...)
  -- add your checks
  orig_trigger_load(...)
end
```

> if we wanted to split dependencies into their own specs rather than bundling them

As I've clarified many times already: Dependency management is *out of scope* for lz.n. In fact, this library is designed with automatic dependency management in mind, and providing users with an API to declare dependencies to influence loading/configuration order *defeats the purpose and has the potential to encourage bad design practices*.

Frankly, I'd appreciate it if you stopped arguing with me whenever you don't get what you want. 
Keep in mind that you don't have to maintain this project.
Please refer to [our code of conduct](https://github.com/nvim-neorocks/lz.n?tab=coc-ov-file#contributor-covenant-code-of-conduct).
