### ISSUE TITLE
cmd with spaces escapes the space

### ISSUE THREAD

**Issue by matthis-k** [nvim-neorocks/lz.n#90]
"Telescope find_files" will become "Telescope\ find_files" which will not execute the command you wanted (if you tab complete it)
(coming from lazy.nvim it at least started off like that and it was in my config, just curious)
Or is the intention to just go with "Telescope"

**Comment by mrcjkb** [comment]
> coming from lazy.nvim it at least started off like that and it was in my config, just curious

I don't understand. Does that work with lazy.nvim?

From Neovim's point of view, `find_files` is not a subcommand. It's an argument to the `Telescope` command. Neovim doesn't have an API for subcommands.

**Comment by mrcjkb** [comment]
Just tested this with lazy.nvim:

```lua
vim.env.LAZY_STDPATH = '.repro'
load(vim.fn.system('curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua'))()

require('lazy.minit').repro {
  spec = {
    {
      'nvim-telescope/telescope.nvim',
      dependencies = { 'nvim-lua/plenary.nvim' },
      cmd = "Telescope find_files",
    },
  },
}
```

It doesn't work there either.
